# Nginx Dockerfile Alpine Image
FROM nginx:alpine

# Copy the Nginx configuration file
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]