# Include the prompts
defaults:
  - prompts.yaml
  - data.yaml

# Individual agent configurations
agents:
  classifier_agent:
    _target_: langchain_core.agents.FunctionAgent
    name: "ClassifierAgent" 
    description: ${prompts.classifier_agent.description}
    system_prompt: ${prompts.classifier_agent.prompt}
    can_handoff_to:
      - "NoRAGAgent"
      - "RAGAgent"
  
  no_rag_agent:
    _target_: langchain_core.agents.FunctionAgent
    name: "NoRAGAgent"
    description: ${prompts.no_rag_agent.description}
    system_prompt: ${prompts.no_rag_agent.prompt}
    can_handoff_to:
      - "ExplainerAgent"
  
  rag_agent:
    _target_: langchain_core.agents.FunctionAgent
    name: "RAGAgent"
    description: ${prompts.rag_agent.description}
    system_prompt: ${prompts.rag_agent.prompt}
    can_handoff_to:
      - "ExplainerAgent"
    tools:
      - _target_: langchain_core.tools.QueryEngineTool.from_defaults
        name: "rag_book_search_tool"
        description: prompts.rag_agent.query_engine_tool.description
        query_engine: ${data.index}
  
  explainer_agent:
    _target_: langchain_core.agents.FunctionAgent
    name: "ExplainerAgent"
    description: ${prompts.explainer_agent.description}
    system_prompt: ${prompts.explainer_agent.prompt}
