# Define the specification for the LLM and embeddings
llm:
  model:
    model_name: "gpt-4"
    temperature: 0.7
    max_tokens: 1000

  embeddings:
    model_name: "text-embedding-3-small"
    dimensions: 1536





