# Include the agents and data
defaults:
  - agents.yaml
  - data.yaml

# Workflow configuration
workflow:
  _target_: llama_index.core.agent.workflow.AgentWorkflow
  root_agent: "ClassifierAgent"
  agents:
    - ${agents.classifier_agent}
    - ${agents.no_rag_agent}
    - ${agents.rag_agent}
    - ${agents.explainer_agent}
  initial_state:
    mode: ""  # rag or no_rag
    rag_items: {}
    no_rag_result: ""
    rag_result: ""
    explainer_result: ""